# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citacione', '0007_location_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
